apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azurefile-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azurefile-provisioner
subjects:
  - kind: ServiceAccount
    name: azurefile-provisioner
    namespace: azurefile-provisioner-system
